# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/michael/git_repos/UnrealEngine
GAMEPROJECTFILE =/home/michael/work/development/DemoProject/DemoProject.uproject

TARGETS = \
	BlankProgram-Linux-Debug  \
	BlankProgram-Linux-DebugGame  \
	BlankProgram-Linux-Shipping  \
	BlankProgram-Linux-Test  \
	BlankProgram \
	BuildPatchTool-Linux-Debug  \
	BuildPatchTool-Linux-DebugGame  \
	BuildPatchTool-Linux-Shipping  \
	BuildPatchTool-Linux-Test  \
	BuildPatchTool \
	CrashReportClient-Linux-Debug  \
	CrashReportClient-Linux-DebugGame  \
	CrashReportClient-Linux-Shipping  \
	CrashReportClient-Linux-Test  \
	CrashReportClient \
	UnrealLaunchDaemon-Linux-Debug  \
	UnrealLaunchDaemon-Linux-DebugGame  \
	UnrealLaunchDaemon-Linux-Shipping  \
	UnrealLaunchDaemon-Linux-Test  \
	UnrealLaunchDaemon \
	LiveCodingConsole-Linux-Debug  \
	LiveCodingConsole-Linux-DebugGame  \
	LiveCodingConsole-Linux-Shipping  \
	LiveCodingConsole-Linux-Test  \
	LiveCodingConsole \
	DsymExporter-Linux-Debug  \
	DsymExporter-Linux-DebugGame  \
	DsymExporter-Linux-Shipping  \
	DsymExporter-Linux-Test  \
	DsymExporter \
	UE4EditorServices-Linux-Debug  \
	UE4EditorServices-Linux-DebugGame  \
	UE4EditorServices-Linux-Shipping  \
	UE4EditorServices-Linux-Test  \
	UE4EditorServices \
	UnrealAtoS-Linux-Debug  \
	UnrealAtoS-Linux-DebugGame  \
	UnrealAtoS-Linux-Shipping  \
	UnrealAtoS-Linux-Test  \
	UnrealAtoS \
	MayaLiveLinkPlugin2016-Linux-Debug  \
	MayaLiveLinkPlugin2016-Linux-DebugGame  \
	MayaLiveLinkPlugin2016-Linux-Shipping  \
	MayaLiveLinkPlugin2016-Linux-Test  \
	MayaLiveLinkPlugin2016 \
	MayaLiveLinkPlugin2017-Linux-Debug  \
	MayaLiveLinkPlugin2017-Linux-DebugGame  \
	MayaLiveLinkPlugin2017-Linux-Shipping  \
	MayaLiveLinkPlugin2017-Linux-Test  \
	MayaLiveLinkPlugin2017 \
	MayaLiveLinkPlugin2018-Linux-Debug  \
	MayaLiveLinkPlugin2018-Linux-DebugGame  \
	MayaLiveLinkPlugin2018-Linux-Shipping  \
	MayaLiveLinkPlugin2018-Linux-Test  \
	MayaLiveLinkPlugin2018 \
	MinidumpDiagnostics-Linux-Debug  \
	MinidumpDiagnostics-Linux-DebugGame  \
	MinidumpDiagnostics-Linux-Shipping  \
	MinidumpDiagnostics-Linux-Test  \
	MinidumpDiagnostics \
	WebRTCProxy-Linux-Debug  \
	WebRTCProxy-Linux-DebugGame  \
	WebRTCProxy-Linux-Shipping  \
	WebRTCProxy-Linux-Test  \
	WebRTCProxy \
	ShaderCompileWorker-Linux-Debug  \
	ShaderCompileWorker-Linux-DebugGame  \
	ShaderCompileWorker-Linux-Shipping  \
	ShaderCompileWorker-Linux-Test  \
	ShaderCompileWorker \
	SlateViewer-Linux-Debug  \
	SlateViewer-Linux-DebugGame  \
	SlateViewer-Linux-Shipping  \
	SlateViewer-Linux-Test  \
	SlateViewer \
	SymbolDebugger-Linux-Debug  \
	SymbolDebugger-Linux-DebugGame  \
	SymbolDebugger-Linux-Shipping  \
	SymbolDebugger-Linux-Test  \
	SymbolDebugger \
	TestPAL-Linux-Debug  \
	TestPAL-Linux-DebugGame  \
	TestPAL-Linux-Shipping  \
	TestPAL-Linux-Test  \
	TestPAL \
	UnrealCEFSubProcess-Linux-Debug  \
	UnrealCEFSubProcess-Linux-DebugGame  \
	UnrealCEFSubProcess-Linux-Shipping  \
	UnrealCEFSubProcess-Linux-Test  \
	UnrealCEFSubProcess \
	UnrealFileServer-Linux-Debug  \
	UnrealFileServer-Linux-DebugGame  \
	UnrealFileServer-Linux-Shipping  \
	UnrealFileServer-Linux-Test  \
	UnrealFileServer \
	UnrealFrontend-Linux-Debug  \
	UnrealFrontend-Linux-DebugGame  \
	UnrealFrontend-Linux-Shipping  \
	UnrealFrontend-Linux-Test  \
	UnrealFrontend \
	UnrealHeaderTool-Linux-Debug  \
	UnrealHeaderTool-Linux-DebugGame  \
	UnrealHeaderTool-Linux-Shipping  \
	UnrealHeaderTool-Linux-Test  \
	UnrealHeaderTool \
	UnrealLightmass-Linux-Debug  \
	UnrealLightmass-Linux-DebugGame  \
	UnrealLightmass-Linux-Shipping  \
	UnrealLightmass-Linux-Test  \
	UnrealLightmass \
	UnrealMultiUserServer-Linux-Debug  \
	UnrealMultiUserServer-Linux-DebugGame  \
	UnrealMultiUserServer-Linux-Shipping  \
	UnrealMultiUserServer-Linux-Test  \
	UnrealMultiUserServer \
	UnrealPak-Linux-Debug  \
	UnrealPak-Linux-DebugGame  \
	UnrealPak-Linux-Shipping  \
	UnrealPak-Linux-Test  \
	UnrealPak \
	UnrealVersionSelector-Linux-Debug  \
	UnrealVersionSelector-Linux-DebugGame  \
	UnrealVersionSelector-Linux-Shipping  \
	UnrealVersionSelector-Linux-Test  \
	UnrealVersionSelector \
	UnrealWatchdog-Linux-Debug  \
	UnrealWatchdog-Linux-DebugGame  \
	UnrealWatchdog-Linux-Shipping  \
	UnrealWatchdog-Linux-Test  \
	UnrealWatchdog \
	BootstrapPackagedGame-Linux-Debug  \
	BootstrapPackagedGame-Linux-DebugGame  \
	BootstrapPackagedGame-Linux-Shipping  \
	BootstrapPackagedGame-Linux-Test  \
	BootstrapPackagedGame \
	UE4Client-Linux-Debug  \
	UE4Client-Linux-DebugGame  \
	UE4Client-Linux-Shipping  \
	UE4Client-Linux-Test  \
	UE4Client \
	UE4Editor-Linux-Debug  \
	UE4Editor-Linux-DebugGame  \
	UE4Editor-Linux-Shipping  \
	UE4Editor-Linux-Test  \
	UE4Editor \
	UE4Game-Linux-Debug  \
	UE4Game-Linux-DebugGame  \
	UE4Game-Linux-Shipping  \
	UE4Game-Linux-Test  \
	UE4Game \
	UE4Server-Linux-Debug  \
	UE4Server-Linux-DebugGame  \
	UE4Server-Linux-Shipping  \
	UE4Server-Linux-Test  \
	UE4Server \
	DemoProject-Linux-Debug  \
	DemoProject-Linux-DebugGame  \
	DemoProject-Linux-Shipping  \
	DemoProject-Linux-Test  \
	DemoProject \
	DemoProjectEditor-Linux-Debug  \
	DemoProjectEditor-Linux-DebugGame  \
	DemoProjectEditor-Linux-Shipping  \
	DemoProjectEditor-Linux-Test  \
	DemoProjectEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/RunMono.sh" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping ShaderCompileWorker UnrealLightmass

StandardSet: RequiredTools UnrealFrontend UE4Editor

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UE4Editor-Linux-Debug


BlankProgram-Linux-Debug:
	 $(BUILD) BlankProgram Linux Debug  $(ARGS)

BlankProgram-Linux-DebugGame:
	 $(BUILD) BlankProgram Linux DebugGame  $(ARGS)

BlankProgram-Linux-Shipping:
	 $(BUILD) BlankProgram Linux Shipping  $(ARGS)

BlankProgram-Linux-Test:
	 $(BUILD) BlankProgram Linux Test  $(ARGS)

BlankProgram:
	 $(BUILD) BlankProgram Linux Development  $(ARGS)

BuildPatchTool-Linux-Debug:
	 $(BUILD) BuildPatchTool Linux Debug  $(ARGS)

BuildPatchTool-Linux-DebugGame:
	 $(BUILD) BuildPatchTool Linux DebugGame  $(ARGS)

BuildPatchTool-Linux-Shipping:
	 $(BUILD) BuildPatchTool Linux Shipping  $(ARGS)

BuildPatchTool-Linux-Test:
	 $(BUILD) BuildPatchTool Linux Test  $(ARGS)

BuildPatchTool:
	 $(BUILD) BuildPatchTool Linux Development  $(ARGS)

CrashReportClient-Linux-Debug:
	 $(BUILD) CrashReportClient Linux Debug  $(ARGS)

CrashReportClient-Linux-DebugGame:
	 $(BUILD) CrashReportClient Linux DebugGame  $(ARGS)

CrashReportClient-Linux-Shipping:
	 $(BUILD) CrashReportClient Linux Shipping  $(ARGS)

CrashReportClient-Linux-Test:
	 $(BUILD) CrashReportClient Linux Test  $(ARGS)

CrashReportClient:
	 $(BUILD) CrashReportClient Linux Development  $(ARGS)

UnrealLaunchDaemon-Linux-Debug:
	 $(BUILD) UnrealLaunchDaemon Linux Debug  $(ARGS)

UnrealLaunchDaemon-Linux-DebugGame:
	 $(BUILD) UnrealLaunchDaemon Linux DebugGame  $(ARGS)

UnrealLaunchDaemon-Linux-Shipping:
	 $(BUILD) UnrealLaunchDaemon Linux Shipping  $(ARGS)

UnrealLaunchDaemon-Linux-Test:
	 $(BUILD) UnrealLaunchDaemon Linux Test  $(ARGS)

UnrealLaunchDaemon:
	 $(BUILD) UnrealLaunchDaemon Linux Development  $(ARGS)

LiveCodingConsole-Linux-Debug:
	 $(BUILD) LiveCodingConsole Linux Debug  $(ARGS)

LiveCodingConsole-Linux-DebugGame:
	 $(BUILD) LiveCodingConsole Linux DebugGame  $(ARGS)

LiveCodingConsole-Linux-Shipping:
	 $(BUILD) LiveCodingConsole Linux Shipping  $(ARGS)

LiveCodingConsole-Linux-Test:
	 $(BUILD) LiveCodingConsole Linux Test  $(ARGS)

LiveCodingConsole:
	 $(BUILD) LiveCodingConsole Linux Development  $(ARGS)

DsymExporter-Linux-Debug:
	 $(BUILD) DsymExporter Linux Debug  $(ARGS)

DsymExporter-Linux-DebugGame:
	 $(BUILD) DsymExporter Linux DebugGame  $(ARGS)

DsymExporter-Linux-Shipping:
	 $(BUILD) DsymExporter Linux Shipping  $(ARGS)

DsymExporter-Linux-Test:
	 $(BUILD) DsymExporter Linux Test  $(ARGS)

DsymExporter:
	 $(BUILD) DsymExporter Linux Development  $(ARGS)

UE4EditorServices-Linux-Debug:
	 $(BUILD) UE4EditorServices Linux Debug  $(ARGS)

UE4EditorServices-Linux-DebugGame:
	 $(BUILD) UE4EditorServices Linux DebugGame  $(ARGS)

UE4EditorServices-Linux-Shipping:
	 $(BUILD) UE4EditorServices Linux Shipping  $(ARGS)

UE4EditorServices-Linux-Test:
	 $(BUILD) UE4EditorServices Linux Test  $(ARGS)

UE4EditorServices:
	 $(BUILD) UE4EditorServices Linux Development  $(ARGS)

UnrealAtoS-Linux-Debug:
	 $(BUILD) UnrealAtoS Linux Debug  $(ARGS)

UnrealAtoS-Linux-DebugGame:
	 $(BUILD) UnrealAtoS Linux DebugGame  $(ARGS)

UnrealAtoS-Linux-Shipping:
	 $(BUILD) UnrealAtoS Linux Shipping  $(ARGS)

UnrealAtoS-Linux-Test:
	 $(BUILD) UnrealAtoS Linux Test  $(ARGS)

UnrealAtoS:
	 $(BUILD) UnrealAtoS Linux Development  $(ARGS)

MayaLiveLinkPlugin2016-Linux-Debug:
	 $(BUILD) MayaLiveLinkPlugin2016 Linux Debug  $(ARGS)

MayaLiveLinkPlugin2016-Linux-DebugGame:
	 $(BUILD) MayaLiveLinkPlugin2016 Linux DebugGame  $(ARGS)

MayaLiveLinkPlugin2016-Linux-Shipping:
	 $(BUILD) MayaLiveLinkPlugin2016 Linux Shipping  $(ARGS)

MayaLiveLinkPlugin2016-Linux-Test:
	 $(BUILD) MayaLiveLinkPlugin2016 Linux Test  $(ARGS)

MayaLiveLinkPlugin2016:
	 $(BUILD) MayaLiveLinkPlugin2016 Linux Development  $(ARGS)

MayaLiveLinkPlugin2017-Linux-Debug:
	 $(BUILD) MayaLiveLinkPlugin2017 Linux Debug  $(ARGS)

MayaLiveLinkPlugin2017-Linux-DebugGame:
	 $(BUILD) MayaLiveLinkPlugin2017 Linux DebugGame  $(ARGS)

MayaLiveLinkPlugin2017-Linux-Shipping:
	 $(BUILD) MayaLiveLinkPlugin2017 Linux Shipping  $(ARGS)

MayaLiveLinkPlugin2017-Linux-Test:
	 $(BUILD) MayaLiveLinkPlugin2017 Linux Test  $(ARGS)

MayaLiveLinkPlugin2017:
	 $(BUILD) MayaLiveLinkPlugin2017 Linux Development  $(ARGS)

MayaLiveLinkPlugin2018-Linux-Debug:
	 $(BUILD) MayaLiveLinkPlugin2018 Linux Debug  $(ARGS)

MayaLiveLinkPlugin2018-Linux-DebugGame:
	 $(BUILD) MayaLiveLinkPlugin2018 Linux DebugGame  $(ARGS)

MayaLiveLinkPlugin2018-Linux-Shipping:
	 $(BUILD) MayaLiveLinkPlugin2018 Linux Shipping  $(ARGS)

MayaLiveLinkPlugin2018-Linux-Test:
	 $(BUILD) MayaLiveLinkPlugin2018 Linux Test  $(ARGS)

MayaLiveLinkPlugin2018:
	 $(BUILD) MayaLiveLinkPlugin2018 Linux Development  $(ARGS)

MinidumpDiagnostics-Linux-Debug:
	 $(BUILD) MinidumpDiagnostics Linux Debug  $(ARGS)

MinidumpDiagnostics-Linux-DebugGame:
	 $(BUILD) MinidumpDiagnostics Linux DebugGame  $(ARGS)

MinidumpDiagnostics-Linux-Shipping:
	 $(BUILD) MinidumpDiagnostics Linux Shipping  $(ARGS)

MinidumpDiagnostics-Linux-Test:
	 $(BUILD) MinidumpDiagnostics Linux Test  $(ARGS)

MinidumpDiagnostics:
	 $(BUILD) MinidumpDiagnostics Linux Development  $(ARGS)

WebRTCProxy-Linux-Debug:
	 $(BUILD) WebRTCProxy Linux Debug  $(ARGS)

WebRTCProxy-Linux-DebugGame:
	 $(BUILD) WebRTCProxy Linux DebugGame  $(ARGS)

WebRTCProxy-Linux-Shipping:
	 $(BUILD) WebRTCProxy Linux Shipping  $(ARGS)

WebRTCProxy-Linux-Test:
	 $(BUILD) WebRTCProxy Linux Test  $(ARGS)

WebRTCProxy:
	 $(BUILD) WebRTCProxy Linux Development  $(ARGS)

ShaderCompileWorker-Linux-Debug:
	 $(BUILD) ShaderCompileWorker Linux Debug  $(ARGS)

ShaderCompileWorker-Linux-DebugGame:
	 $(BUILD) ShaderCompileWorker Linux DebugGame  $(ARGS)

ShaderCompileWorker-Linux-Shipping:
	 $(BUILD) ShaderCompileWorker Linux Shipping  $(ARGS)

ShaderCompileWorker-Linux-Test:
	 $(BUILD) ShaderCompileWorker Linux Test  $(ARGS)

ShaderCompileWorker:
	 $(BUILD) ShaderCompileWorker Linux Development  $(ARGS)

SlateViewer-Linux-Debug:
	 $(BUILD) SlateViewer Linux Debug  $(ARGS)

SlateViewer-Linux-DebugGame:
	 $(BUILD) SlateViewer Linux DebugGame  $(ARGS)

SlateViewer-Linux-Shipping:
	 $(BUILD) SlateViewer Linux Shipping  $(ARGS)

SlateViewer-Linux-Test:
	 $(BUILD) SlateViewer Linux Test  $(ARGS)

SlateViewer:
	 $(BUILD) SlateViewer Linux Development  $(ARGS)

SymbolDebugger-Linux-Debug:
	 $(BUILD) SymbolDebugger Linux Debug  $(ARGS)

SymbolDebugger-Linux-DebugGame:
	 $(BUILD) SymbolDebugger Linux DebugGame  $(ARGS)

SymbolDebugger-Linux-Shipping:
	 $(BUILD) SymbolDebugger Linux Shipping  $(ARGS)

SymbolDebugger-Linux-Test:
	 $(BUILD) SymbolDebugger Linux Test  $(ARGS)

SymbolDebugger:
	 $(BUILD) SymbolDebugger Linux Development  $(ARGS)

TestPAL-Linux-Debug:
	 $(BUILD) TestPAL Linux Debug  $(ARGS)

TestPAL-Linux-DebugGame:
	 $(BUILD) TestPAL Linux DebugGame  $(ARGS)

TestPAL-Linux-Shipping:
	 $(BUILD) TestPAL Linux Shipping  $(ARGS)

TestPAL-Linux-Test:
	 $(BUILD) TestPAL Linux Test  $(ARGS)

TestPAL:
	 $(BUILD) TestPAL Linux Development  $(ARGS)

UnrealCEFSubProcess-Linux-Debug:
	 $(BUILD) UnrealCEFSubProcess Linux Debug  $(ARGS)

UnrealCEFSubProcess-Linux-DebugGame:
	 $(BUILD) UnrealCEFSubProcess Linux DebugGame  $(ARGS)

UnrealCEFSubProcess-Linux-Shipping:
	 $(BUILD) UnrealCEFSubProcess Linux Shipping  $(ARGS)

UnrealCEFSubProcess-Linux-Test:
	 $(BUILD) UnrealCEFSubProcess Linux Test  $(ARGS)

UnrealCEFSubProcess:
	 $(BUILD) UnrealCEFSubProcess Linux Development  $(ARGS)

UnrealFileServer-Linux-Debug:
	 $(BUILD) UnrealFileServer Linux Debug  $(ARGS)

UnrealFileServer-Linux-DebugGame:
	 $(BUILD) UnrealFileServer Linux DebugGame  $(ARGS)

UnrealFileServer-Linux-Shipping:
	 $(BUILD) UnrealFileServer Linux Shipping  $(ARGS)

UnrealFileServer-Linux-Test:
	 $(BUILD) UnrealFileServer Linux Test  $(ARGS)

UnrealFileServer:
	 $(BUILD) UnrealFileServer Linux Development  $(ARGS)

UnrealFrontend-Linux-Debug:
	 $(BUILD) UnrealFrontend Linux Debug  $(ARGS)

UnrealFrontend-Linux-DebugGame:
	 $(BUILD) UnrealFrontend Linux DebugGame  $(ARGS)

UnrealFrontend-Linux-Shipping:
	 $(BUILD) UnrealFrontend Linux Shipping  $(ARGS)

UnrealFrontend-Linux-Test:
	 $(BUILD) UnrealFrontend Linux Test  $(ARGS)

UnrealFrontend:
	 $(BUILD) UnrealFrontend Linux Development  $(ARGS)

UnrealHeaderTool-Linux-Debug:
	 $(BUILD) UnrealHeaderTool Linux Debug  $(ARGS)

UnrealHeaderTool-Linux-DebugGame:
	 $(BUILD) UnrealHeaderTool Linux DebugGame  $(ARGS)

UnrealHeaderTool-Linux-Shipping:
	 $(BUILD) UnrealHeaderTool Linux Shipping  $(ARGS)

UnrealHeaderTool-Linux-Test:
	 $(BUILD) UnrealHeaderTool Linux Test  $(ARGS)

UnrealHeaderTool:
	 $(BUILD) UnrealHeaderTool Linux Development  $(ARGS)

UnrealLightmass-Linux-Debug:
	 $(BUILD) UnrealLightmass Linux Debug  $(ARGS)

UnrealLightmass-Linux-DebugGame:
	 $(BUILD) UnrealLightmass Linux DebugGame  $(ARGS)

UnrealLightmass-Linux-Shipping:
	 $(BUILD) UnrealLightmass Linux Shipping  $(ARGS)

UnrealLightmass-Linux-Test:
	 $(BUILD) UnrealLightmass Linux Test  $(ARGS)

UnrealLightmass:
	 $(BUILD) UnrealLightmass Linux Development  $(ARGS)

UnrealMultiUserServer-Linux-Debug:
	 $(BUILD) UnrealMultiUserServer Linux Debug  $(ARGS)

UnrealMultiUserServer-Linux-DebugGame:
	 $(BUILD) UnrealMultiUserServer Linux DebugGame  $(ARGS)

UnrealMultiUserServer-Linux-Shipping:
	 $(BUILD) UnrealMultiUserServer Linux Shipping  $(ARGS)

UnrealMultiUserServer-Linux-Test:
	 $(BUILD) UnrealMultiUserServer Linux Test  $(ARGS)

UnrealMultiUserServer:
	 $(BUILD) UnrealMultiUserServer Linux Development  $(ARGS)

UnrealPak-Linux-Debug:
	 $(BUILD) UnrealPak Linux Debug  $(ARGS)

UnrealPak-Linux-DebugGame:
	 $(BUILD) UnrealPak Linux DebugGame  $(ARGS)

UnrealPak-Linux-Shipping:
	 $(BUILD) UnrealPak Linux Shipping  $(ARGS)

UnrealPak-Linux-Test:
	 $(BUILD) UnrealPak Linux Test  $(ARGS)

UnrealPak:
	 $(BUILD) UnrealPak Linux Development  $(ARGS)

UnrealVersionSelector-Linux-Debug:
	 $(BUILD) UnrealVersionSelector Linux Debug  $(ARGS)

UnrealVersionSelector-Linux-DebugGame:
	 $(BUILD) UnrealVersionSelector Linux DebugGame  $(ARGS)

UnrealVersionSelector-Linux-Shipping:
	 $(BUILD) UnrealVersionSelector Linux Shipping  $(ARGS)

UnrealVersionSelector-Linux-Test:
	 $(BUILD) UnrealVersionSelector Linux Test  $(ARGS)

UnrealVersionSelector:
	 $(BUILD) UnrealVersionSelector Linux Development  $(ARGS)

UnrealWatchdog-Linux-Debug:
	 $(BUILD) UnrealWatchdog Linux Debug  $(ARGS)

UnrealWatchdog-Linux-DebugGame:
	 $(BUILD) UnrealWatchdog Linux DebugGame  $(ARGS)

UnrealWatchdog-Linux-Shipping:
	 $(BUILD) UnrealWatchdog Linux Shipping  $(ARGS)

UnrealWatchdog-Linux-Test:
	 $(BUILD) UnrealWatchdog Linux Test  $(ARGS)

UnrealWatchdog:
	 $(BUILD) UnrealWatchdog Linux Development  $(ARGS)

BootstrapPackagedGame-Linux-Debug:
	 $(BUILD) BootstrapPackagedGame Linux Debug  $(ARGS)

BootstrapPackagedGame-Linux-DebugGame:
	 $(BUILD) BootstrapPackagedGame Linux DebugGame  $(ARGS)

BootstrapPackagedGame-Linux-Shipping:
	 $(BUILD) BootstrapPackagedGame Linux Shipping  $(ARGS)

BootstrapPackagedGame-Linux-Test:
	 $(BUILD) BootstrapPackagedGame Linux Test  $(ARGS)

BootstrapPackagedGame:
	 $(BUILD) BootstrapPackagedGame Linux Development  $(ARGS)

UE4Client-Linux-Debug:
	 $(BUILD) UE4Client Linux Debug  $(ARGS)

UE4Client-Linux-DebugGame:
	 $(BUILD) UE4Client Linux DebugGame  $(ARGS)

UE4Client-Linux-Shipping:
	 $(BUILD) UE4Client Linux Shipping  $(ARGS)

UE4Client-Linux-Test:
	 $(BUILD) UE4Client Linux Test  $(ARGS)

UE4Client:
	 $(BUILD) UE4Client Linux Development  $(ARGS)

UE4Editor-Linux-Debug:
	 $(BUILD) UE4Editor Linux Debug  $(ARGS)

UE4Editor-Linux-DebugGame:
	 $(BUILD) UE4Editor Linux DebugGame  $(ARGS)

UE4Editor-Linux-Shipping:
	 $(BUILD) UE4Editor Linux Shipping  $(ARGS)

UE4Editor-Linux-Test:
	 $(BUILD) UE4Editor Linux Test  $(ARGS)

UE4Editor:
	 $(BUILD) UE4Editor Linux Development  $(ARGS)

UE4Game-Linux-Debug:
	 $(BUILD) UE4Game Linux Debug  $(ARGS)

UE4Game-Linux-DebugGame:
	 $(BUILD) UE4Game Linux DebugGame  $(ARGS)

UE4Game-Linux-Shipping:
	 $(BUILD) UE4Game Linux Shipping  $(ARGS)

UE4Game-Linux-Test:
	 $(BUILD) UE4Game Linux Test  $(ARGS)

UE4Game:
	 $(BUILD) UE4Game Linux Development  $(ARGS)

UE4Server-Linux-Debug:
	 $(BUILD) UE4Server Linux Debug  $(ARGS)

UE4Server-Linux-DebugGame:
	 $(BUILD) UE4Server Linux DebugGame  $(ARGS)

UE4Server-Linux-Shipping:
	 $(BUILD) UE4Server Linux Shipping  $(ARGS)

UE4Server-Linux-Test:
	 $(BUILD) UE4Server Linux Test  $(ARGS)

UE4Server:
	 $(BUILD) UE4Server Linux Development  $(ARGS)

DemoProject-Linux-Debug:
	 $(PROJECTBUILD) DemoProject Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DemoProject-Linux-DebugGame:
	 $(PROJECTBUILD) DemoProject Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DemoProject-Linux-Shipping:
	 $(PROJECTBUILD) DemoProject Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DemoProject-Linux-Test:
	 $(PROJECTBUILD) DemoProject Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DemoProject:
	 $(PROJECTBUILD) DemoProject Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DemoProjectEditor-Linux-Debug:
	 $(PROJECTBUILD) DemoProjectEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DemoProjectEditor-Linux-DebugGame:
	 $(PROJECTBUILD) DemoProjectEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DemoProjectEditor-Linux-Shipping:
	 $(PROJECTBUILD) DemoProjectEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DemoProjectEditor-Linux-Test:
	 $(PROJECTBUILD) DemoProjectEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DemoProjectEditor:
	 $(PROJECTBUILD) DemoProjectEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
